# Generated by Django 5.2.9 on 2026-01-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustome",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="usercustome",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
