# Generated by Django 5.2.9 on 2026-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercustome",
            name="role",
            field=models.CharField(
                choices=[("shopkeeper", "shopkeeper"), ("customer", "customer")],
                max_length=20,
            ),
        ),
    ]
